seed: 42
device: 'cuda:0'

dir:
  seg:         '/media/dysk_a/jr_buler/HAM10000/train/HAM10000_segmentations/'
  img:         '/media/dysk_a/jr_buler/HAM10000/train/HAM10000_images/'
  csv:         '/media/dysk_a/jr_buler/HAM10000/train/HAM10000_metadata'
  pkl_train:   '/media/dysk_a/jr_buler/HAM10000/my_pickle/train_radiomic_features.pkl'
  pkl_val:     '/media/dysk_a/jr_buler/HAM10000/my_pickle/val_radiomic_features.pkl'
  pkl_test:    '/media/dysk_a/jr_buler/HAM10000/my_pickle/test_radiomic_features.pkl'
  inf:         '/media/dysk_a/jr_buler/HAM10000/my_pickle/info.txt'

dataset:
  split_fraction_train_rest: 0.7
  split_fraction_val_test: 0.5
  img_size: 224 #384
  k_folds: 10
  train_sampling:
    method: 'none' # oversample, undersample none
    multiplier: 1.0 # 0. to 1. value 1.0 means no change (applicable in undersampling scenario)

radiomics:
  extract: False # True, False, if False load from pkl
  mode: 'parallel' #serial, parallel
  save: False # True, False

net_train:
  # TODO
  optimizer: 'sgd' # adam, sgd
  criterion: 'ce' # bce, ce
  scheduler: 'linear' # linear, step, plateau
  #
  epochs: 1000
  patience: 50
  batch_size: 24
  lr: 0.001
  wd: 0.001