neptune: True

seed: 42
device: 'cuda:0'

dir:
  seg:         '/media/dysk_a/jr_buler/HAM10000/train/new/HAM10000_segmentations/'

  img:         '/media/dysk_a/jr_buler/HAM10000/train/new/HAM10000_images/'
  seg_test:    '/media/dysk_a/jr_buler/HAM10000/test/new/ISIC2018_Task3_Test_Images_Segmentations_trained_on_HAM/'  
  img_test:    '/media/dysk_a/jr_buler/HAM10000/test/new/ISIC2018_Task3_Test_Images/'
  
  # img:         '/media/dysk_a/jr_buler/HAM10000/train/new/HAM10000_images_no_hair/'
  # seg_test:    '/media/dysk_a/jr_buler/HAM10000/test/new/ISIC2018_Task3_Test_Images_Segmentations_trained_on_HAM_no_hair/'  
  # img_test:    '/media/dysk_a/jr_buler/HAM10000/test/new/ISIC2018_Task3_Test_Images_no_hair/'
  
  new_metadata:      '/media/dysk_a/jr_buler/HAM10000/train/HAM10000_metadata_new.csv'
  new_metadata_test: '/media/dysk_a/jr_buler/HAM10000/test/ISIC2018_Task3_Test_GroundTruth_new.csv'

  csv:         '/media/dysk_a/jr_buler/HAM10000/train/HAM10000_metadata'
  csv_test:    '/media/dysk_a/jr_buler/HAM10000/test/ISIC2018_Task3_Test_GroundTruth.csv'
  pkl_train:   '/media/dysk_a/jr_buler/HAM10000/my_pickle/train_radiomic_features.pkl'
  pkl_val:     '/media/dysk_a/jr_buler/HAM10000/my_pickle/val_radiomic_features.pkl'
  pkl_test:    '/media/dysk_a/jr_buler/HAM10000/my_pickle/test_radiomic_features.pkl'
  inf:         '/media/dysk_a/jr_buler/HAM10000/my_pickle/info.txt'
  models:      '/media/dysk_a/jr_buler/HAM10000/models/'
  results:     '/media/dysk_a/jr_buler/HAM10000/results/'
  results2:     '/media/dysk_a/jr_buler/HAM10000/results2/'

dataset:
  mode: 'hybrid' # images, radiomics, hybrid
  split_fraction_train_rest: 0.7 # not used in k-folds
  split_fraction_val_test: 0.5   # not used in k-folds
  img_size: 224 #384
  k_folds: 5
  train_sampling:
    method: 'none' # oversample, undersample none
    multiplier: 1.0 # 0. to 1. value 1.0 means no change (applicable in undersampling scenario)

radiomics:
  extract: True # True, False, if False load from pkl
  mode: 'serial' #serial, parallel
  gray: True # True, False
  rgb: True # True, False
  save: True # True, False

net_train:
  backbone: 'efficientnet_b0' # resnet34, efficientnet_b0
  optimizer: 'sgd' # adam, sgd
  criterion: 'ce' # bce, ce
  scheduler: 'linear' # linear, step, plateau
  #
  epochs: 1000
  patience: 50
  batch_size: 32
  num_workers: 5
  lr: 0.001
  wd: 0.001